"""Train the tiny character-level transformer on the embedded sonnet corpus.

Run from the repo root:

    python projects/char_transformer_tiny/src/ct_train.py

Writes reports/training_report.md (config, loss trace, wall time, sample generations).
Deterministic under the fixed seed; no downloads, no CLI flags.
"""

from __future__ import annotations

import time
from pathlib import Path

import numpy as np
from ct_model import Adam, CTConfig, generate, init_params, loss_and_grads

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CORPUS_PATH = PROJECT_ROOT / "data" / "corpus.txt"
REPORT_PATH = PROJECT_ROOT / "reports" / "training_report.md"

SEED = 42
BLOCK_SIZE = 32
D_MODEL = 48
D_FF = 96
BATCH_SIZE = 64
N_STEPS = 400
LEARNING_RATE = 3e-3
LOG_EVERY = 25


def load_corpus() -> tuple[np.ndarray, dict[str, int], dict[int, str]]:
    """Read the embedded corpus and encode it as an int array over its own charset."""
    text = CORPUS_PATH.read_text(encoding="utf-8")
    charset = sorted(set(text))
    stoi = {ch: i for i, ch in enumerate(charset)}
    itos = {i: ch for i, ch in enumerate(charset)}
    data = np.array([stoi[ch] for ch in text], dtype=np.int64)
    return data, stoi, itos


def get_batch(
    data: np.ndarray, rng: np.random.Generator, batch_size: int, block_size: int
) -> tuple[np.ndarray, np.ndarray]:
    """Sample random contiguous windows: inputs and next-token targets."""
    starts = rng.integers(0, len(data) - block_size - 1, size=batch_size)
    x = np.stack([data[s : s + block_size] for s in starts])
    y = np.stack([data[s + 1 : s + block_size + 1] for s in starts])
    return x, y


def decode(ids: list[int], itos: dict[int, str]) -> str:
    return "".join(itos[i] for i in ids)


def main() -> None:
    rng = np.random.default_rng(SEED)
    data, stoi, itos = load_corpus()
    config = CTConfig(vocab_size=len(stoi), block_size=BLOCK_SIZE, d_model=D_MODEL, d_ff=D_FF)
    params = init_params(config, rng)
    optimizer = Adam(params, lr=LEARNING_RATE)

    n_params = sum(p.size for p in params.values())
    baseline = float(np.log(config.vocab_size))
    print(f"corpus: {len(data)} chars, vocab {config.vocab_size}, params {n_params}")
    print(f"uniform baseline loss ln(vocab) = {baseline:.4f}")

    loss_trace: list[tuple[int, float]] = []
    start = time.perf_counter()
    for step in range(1, N_STEPS + 1):
        x, y = get_batch(data, rng, BATCH_SIZE, BLOCK_SIZE)
        loss, grads = loss_and_grads(params, x, y, config)
        optimizer.step(params, grads)
        if step == 1 or step % LOG_EVERY == 0:
            loss_trace.append((step, loss))
            print(f"step {step:4d}  loss {loss:.4f}")
    wall_time = time.perf_counter() - start
    print(f"wall time: {wall_time:.1f}s")

    prompt = "Shall I "
    prompt_ids = [stoi[ch] for ch in prompt]
    gen_rng = np.random.default_rng(SEED)
    samples = [
        ("greedy", decode(generate(params, config, prompt_ids, 120, gen_rng), itos)),
        (
            "temperature 0.8",
            decode(generate(params, config, prompt_ids, 120, gen_rng, temperature=0.8), itos),
        ),
        (
            "temperature 1.0",
            decode(generate(params, config, prompt_ids, 120, gen_rng, temperature=1.0), itos),
        ),
    ]
    for name, text in samples:
        print(f"\n--- {name} ---\n{text}")

    write_report(config, n_params, baseline, loss_trace, wall_time, samples)
    print(f"\nreport written to {REPORT_PATH}")


def write_report(
    config: CTConfig,
    n_params: int,
    baseline: float,
    loss_trace: list[tuple[int, float]],
    wall_time: float,
    samples: list[tuple[str, str]],
) -> None:
    lines = [
        "# Training report — char_transformer_tiny",
        "",
        f"Generated by `src/ct_train.py` (seed {SEED}, deterministic).",
        "",
        "## Config",
        "",
        "| Setting | Value |",
        "|---|---|",
        f"| vocab_size | {config.vocab_size} |",
        f"| block_size | {config.block_size} |",
        f"| d_model | {config.d_model} |",
        f"| d_ff | {config.d_ff} |",
        f"| batch_size | {BATCH_SIZE} |",
        f"| steps | {N_STEPS} |",
        f"| optimizer | Adam (local), lr={LEARNING_RATE} |",
        f"| parameters | {n_params} |",
        f"| uniform baseline $\\ln V$ | {baseline:.4f} |",
        f"| wall time | {wall_time:.1f} s |",
        "",
        "## Loss trace",
        "",
        "| Step | Train loss |",
        "|---|---|",
    ]
    lines += [f"| {step} | {loss:.4f} |" for step, loss in loss_trace]
    lines += [
        "",
        f"Loss falls from {loss_trace[0][1]:.4f} (near the uniform baseline "
        f"{baseline:.4f}) to {loss_trace[-1][1]:.4f}.",
        "",
        "## Sample generations",
        "",
        'Prompt: `"Shall I "`, 120 new characters each, generation seed 42.',
        "",
    ]
    for name, text in samples:
        lines += [f"### {name}", "", "```text", text, "```", ""]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
